sudo: required
services:
  - docker

before_install:
  - docker build -t gaganbhullar/frontend -f Dockerfile.dev .

script:
  - docker run -e CI=true gaganbhullar/frontend npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-2-957775997623"
  bucket_path: "docker"
  on:
    branch: "master"
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY